### ISSUE TITLE
Milestone 3 feedback

### ISSUE THREAD

**Issue by gzzen** [Dokkaebi10/dsci-310-group-18#96]
# Milestone 3
- [x] Please re-format the dependencies section in the `README.md` file into a more readable form (-1)
- [x] Please improve the functionality of `make clean`. `notebook/_build`, as a part of output file, should also be removed (-1)
- [x] Command `make all` failed because of missing dependencies (-2)
```
Error in `check_installs()`:
! Some package installs are required: 
• 'kknn', 'kknn'
```
- [x] Docker image https://hub.docker.com/r/leuneri/dsci-310-group-18 is out of date (last update is a month ago). The Github action script only builds the image, but does not push to docker hub. This is making the project not reproducible using the given instruction (-4)
- [x] Please include more detailed instruction in the procedure of generating the report, i.e., where to find the analysis output and report, how to use `make clean`, assuming that the viewer knows nothing about the project structure (-2)
- [x] Step 5 in "Usage" is no longer needed, since Makefile will do the job instead (-1)

# Addressment of previous feedback
The parts that appeared on previous milestone feedback, and has been addressed adequately is labelled with `addressed`, and 50% marks are given back.
- #26 (All addressed) (+0.5)
- #52 (+0.5)
